### PR TITLE
format python code using autopep8 and add pylint

### PR DESCRIPTION
**Pull request by jasonhe258**
Format python code using autopep8 and add pylint

### CODE REVIEW

**Comment by jasonhe258** [comment]
@depenglee1707 @SeanHH86 we need to pay attention the below errors which are exposed by pylint changes:
```
% pylint --rcfile=tests/pylint.conf $(git ls-files '*.py')
************* Module llmserve.backend.llm.ft.transformer
llmserve/backend/llm/ft/transformer.py:15:0: E0611: No name 'TransformersTrainer' in module 'ray.train.huggingface' (no-name-in-module)
llmserve/backend/llm/ft/transformer.py:21:0: E0611: No name 'TransformersCheckpoint' in module 'ray.train.huggingface' (no-name-in-module)
************* Module llmserve.backend.llm.pipelines.llamacpp.processors
llmserve/backend/llm/pipelines/llamacpp/processors.py:20:15: E1136: Value 'scores' is unsubscriptable (unsubscriptable-object)

------------------------------------------------------------------
Your code has been rated at 9.96/10 (previous run: 6.02/10, +3.95)
```

**Comment by SeanHH86** [comment]
It's ok to remove ft.

**Comment by jasonhe258** [comment]
> It's ok to remove ft.

@SeanHH86 Yeah, agree with you, remove the FT in https://github.com/OpenCSGs/llm-inference/pull/13

**Comment by jasonhe258** [comment]
@SeanHH86 @depenglee1707 I think the PR is ready to go now. Thanks.

**Comment by jasonhe258** [comment]
Thanks @SeanHH86

**Pull request merged**
